apiVersion: v1
kind: Pod
metadata:
  name: k6-test
  namespace: autoally
spec:
  restartPolicy: Never
  containers:
  - name: k6
    image: grafana/k6:latest
    command: ["k6", "run", "/scripts/test-pagination-only.js"]
    env:
    - name: BASE_URL
      value: "http://api-gateway"
    - name: KEYCLOAK_URL
      value: "http://keycloak:8080"
    volumeMounts:
    - name: scripts
      mountPath: /scripts
  volumes:
  - name: scripts
    configMap:
      name: k6-scripts
