apiVersion: v1
kind: Pod
metadata:
  name: k6-test
  namespace: autoally
spec:
  containers:
  - name: k6
    image: grafana/k6:latest
    command: ["k6", "run", "/scripts/autoally-load-test.js"]
    env:
    - name: BASE_URL
      value: "http://api-gateway"
    - name: KEYCLOAK_URL
      value: "http://keycloak:8080"
    volumeMounts:
    - name: k6-scripts
      mountPath: /scripts
  volumes:
  - name: k6-scripts
    configMap:
      name: k6-scripts
  restartPolicy: Never
